setTimeout(function() {
	$(".animar-interno1").addClass("animated fadeInLeft");
}, 2200);
setTimeout(function() {
	$(".animar-interno2").addClass("animated fadeInLeft");
}, 2500);
setTimeout(function() {
	$(".animar-interno3").addClass("animated fadeInLeft");
}, 2800);